In [1]:
import numpy as np

In [2]:
a = [[1,2,3], [4,5,6],[7,8,9]]
np.array(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
b = np.arange(0,12,3)
b

array([0, 3, 6, 9])

In [10]:
c = np.linspace(0,10,3)
c

array([ 0.,  5., 10.])

In [ ]:
np.ra